CC = gcc -Wall

zad1: clean
	$(CC) zad1.c -o zad1
	./zad1 'd' 'f' wejscie.txt wyjscie.txt

zad2: clean
	$(CC) zad2.c -o zad2
	./zad2 wejscie.txt wyjscie.txt 1

zad3: clean
	$(CC) zad3.c -o zad3
	./zad3

zad4: clean
	$(CC) zad4.c -o zad4
	./zad4 ./
	
clean:
	rm -f zad1 *.o