CC = gcc -Wall

zad1: clean
	$(CC) zad1.c -o zad1
	./zad1 5

zad2: clean
	$(CC) zad2.c -o zad2
	./zad2 /home/adamtrybus/sysopy

zad3: clean
	$(CC) zad3.c -o zad3
	./zad3 .. '#include <stdio.h>'

clean:
	rm -f zad1 *.o